Fixed context bug "AttributeError: 'SpaceDopeSheetEditor' object has no attribute 'image'" (#160)
When the context is something other than the Image Editor, the panel throws an error about missing the 'image' attribute